// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpCgDplzcuss_pYoUmCg6-5Vcg07hs4N0',
    appId: '1:406571227857:web:ccbe7a21da24d286a603f0',
    messagingSenderId: '406571227857',
    projectId: 'izinto-domestically',
    authDomain: 'izinto-domestically.firebaseapp.com',
    storageBucket: 'izinto-domestically.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQY8tW-zImz3hIPxw8z5QgQErJRl1NHrk',
    appId: '1:406571227857:android:bf668e008a629a41a603f0',
    messagingSenderId: '406571227857',
    projectId: 'izinto-domestically',
    storageBucket: 'izinto-domestically.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sKNrHo7R7GhokmWp_-oZgx2fBitKNgk',
    appId: '1:406571227857:ios:89bf7978b35fa4eaa603f0',
    messagingSenderId: '406571227857',
    projectId: 'izinto-domestically',
    storageBucket: 'izinto-domestically.appspot.com',
    iosClientId: '406571227857-j2ou5ifu9jvlr5mbhgm2l6hnnie67v94.apps.googleusercontent.com',
    iosBundleId: 'izinto.africa.app',
  );
}
